load("@io_bazel_rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "sample",
    srcs = [
        "aoc01.go",
        "aoc02.go",
        "main.go",
    ],
    data = ["//resources:resources"],
)
